### PR TITLE
Added scripts to load the sanitised JSON data.

### PR DESCRIPTION
**Pull request by MatthewJA**
These scripts are pretty simple but will help maintain consistency.

### CODE REVIEW

**Comment by MatthewJA** [comment]
(I'm aware that I have push access now, but I am under the impression that we're still using pull requests as long as my fork exists.)

**Comment by chengsoonong** [comment]
Please update the documentation to show:
- 3 files that Julie provided
- what to run to get an "internal" representation

**Comment by MatthewJA** [comment]
Updated the wiki to talk about the files and setting them up to mirror my local version. When I know more about manipulating this data, I'll include that too.

**Comment by chengsoonong** [comment]
Unfortunately the wiki isn't part of the main repository (it is a separate repository). For now, merge everything into the main documentation (see issue #11).

**Pull request merged**
